### ISSUE TITLE
Actions: Style Checker and Rspec

### ISSUE THREAD

**Issue by mattzollinhofer** [iotait/fundraising#3]
- use https://github.com/testdouble/standard

**Comment by tannerwernecke** [comment]
Adding this style checker to Github to run automatically with a PR seems to be non-trivial. I can definitely go about doing it if it would be worthwhile, but if not, I have standardrb and can use it locally to check before each PR.

Here is what seems to be the best walkthrough for going about adding it to Github:
https://developer.github.com/apps/quickstart-guides/creating-ci-tests-with-the-checks-api/
